/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SnapshotReference
 */
export type SnapshotReference = {
    /**
     *
     * @type {string}
     * @memberof SnapshotReference
     */
    type: "tag" | "branch";
    /**
     *
     * @type {number}
     * @memberof SnapshotReference
     */
    "snapshot-id": number;
    /**
     *
     * @type {number}
     * @memberof SnapshotReference
     */
    "max-ref-age-ms"?: number;
    /**
     *
     * @type {number}
     * @memberof SnapshotReference
     */
    "max-snapshot-age-ms"?: number;
    /**
     *
     * @type {number}
     * @memberof SnapshotReference
     */
    "min-snapshots-to-keep"?: number;
}

