/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetadataLogInner } from "./MetadataLogInner";
import { PartitionSpec } from "./PartitionSpec";
import { Schema } from "./Schema";
import { Snapshot } from "./Snapshot";
import { SnapshotLogInner } from "./SnapshotLogInner";
import { SnapshotReference } from "./SnapshotReference";
import { SortOrder } from "./SortOrder";

/**
 *
 * @export
 * @interface TableMetadata
 */
export type TableMetadata = {
    /**
     *
     * @type {number}
     * @memberof TableMetadata
     */
    "format-version": number;
    /**
     *
     * @type {string}
     * @memberof TableMetadata
     */
    "table-uuid": string;
    /**
     *
     * @type {string}
     * @memberof TableMetadata
     */
    "last-sequence-number": string
    /**
     *
     * @type {string}
     * @memberof TableMetadata
     */
    location?: string;
    /**
     *
     * @type {number}
     * @memberof TableMetadata
     */
    "last-updated-ms"?: number;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof TableMetadata
     */
    properties?: {
        [key: string]: string;
    };
    /**
     *
     * @type {Array<Schema>}
     * @memberof TableMetadata
     */
    schemas?: Array<Schema>;
    /**
     *
     * @type {number}
     * @memberof TableMetadata
     */
    "current-schema-id"?: number;
    /**
     *
     * @type {number}
     * @memberof TableMetadata
     */
    "last-column-id"?: number;
    /**
     *
     * @type {Array<PartitionSpec>}
     * @memberof TableMetadata
     */
    "partition-specs"?: Array<PartitionSpec>;
    /**
     *
     * @type {number}
     * @memberof TableMetadata
     */
    "default-spec-id"?: number;
    /**
     *
     * @type {number}
     * @memberof TableMetadata
     */
    "last-partition-id"?: number;
    /**
     *
     * @type {Array<SortOrder>}
     * @memberof TableMetadata
     */
    "sort-orders"?: Array<SortOrder>;
    /**
     *
     * @type {number}
     * @memberof TableMetadata
     */
    "default-sort-order-id"?: number;
    /**
     *
     * @type {Array<Snapshot>}
     * @memberof TableMetadata
     */
    snapshots?: Array<Snapshot>;
    /**
     *
     * @type {{ [key: string]: SnapshotReference; }}
     * @memberof TableMetadata
     */
    refs?: {
        [key: string]: SnapshotReference;
    };
    /**
     *
     * @type {number}
     * @memberof TableMetadata
     */
    "current-snapshot-id"?: number;
    /**
     *
     * @type {Array<SnapshotLogInner>}
     * @memberof TableMetadata
     */
    "snapshot-log"?: Array<SnapshotLogInner>;
    /**
     *
     * @type {Array<MetadataLogInner>}
     * @memberof TableMetadata
     */
    "metadata-log"?: Array<MetadataLogInner>;
}